### ISSUE TITLE
Release dos-gdc-lambda

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/team-lighthouse-point#162]

**Comment by cricketsloan** [comment]
➤ David Steinberg commented:

The docs currently list the lambda URL, but should point to a well formed DNS entry.

**Comment by david4096** [comment]
https://github.com/DataBiosphere/dos-gdc-lambda/issues/13

**Comment by cricketsloan** [comment]
➤ Cricket Sloan commented:

This seems like we just need a docs update?  Is that right?

**Comment by cricketsloan** [comment]
➤ Natan Lao commented:

[https://github.com/DataBiosphere/dos-gdc-lambda/pull/14](https://github.com/DataBiosphere/dos-gdc-lambda/pull/14)

**Comment by cricketsloan** [comment]
➤ David Steinberg commented:

Got it\!

**Comment by cricketsloan** [comment]
➤ David Steinberg commented:

[https://github.com/DataBiosphere/dos-gdc-lambda/releases/tag/0.1.2](https://github.com/DataBiosphere/dos-gdc-lambda/releases/tag/0.1.2)
