### ISSUE TITLE
Alastair to provide update on AWS bucket access

### ISSUE THREAD

**Issue by briandoconnor** [DataBiosphere/team-lighthouse-point#3]

**Comment by briandoconnor** [comment]
Hi Alastair,

I just wanted to check in with you and see how the meeting with the Data Commons co-chairs went on Tuesday.  Did they green light the 5 studies + GTEx and MOD data as you suspected they would?

Thanks very much for the update!!

Brian

On Fri, Jan 5, 2018 at 9:30 AM, Thomson, Alastair (NIH/NHLBI) [E] <alastair.thomson@nih.gov> wrote:
The IRB issue is study dependent, not CSP. We are working to eliminate the requirement but it will take a couple of months.

 

There’s a meeting with the Data Common co-chairs (IC directors) on Tuesday morning, we hope to get the green light there for the 5 studies + GTEx and MODs.

 

I completely agree with you concern and I’ve conveyed that the leadership. They get it but the best they could offer was “They should work to make sure it’s all the same”… Go figure..

 

A

--
Alastair Thomson
Chief Information Officer
National Heart, Lung, and Blood Institute

 

 

On 1/5/18, 11:35 AM, thus spake "Brian O'Connor" <broconno@ucsc.edu>:

 

Thanks for the update Alastair!

 

Does this IRB issue just cover AWS access or will this affect access to Goncalo's copy in Google too?

 

Would it be possible to expedite access to the 5?  Even though they lack a lot of phenotypic data, having real data files and metadata files will really help us mock up datasets for further testing.  My fear is, without having any access to real data/metadata, our mock data/metadata won't accurately reflect what the real data/metadata actually looks like.

 

Thanks so much for all your help on this!!

 

Brian

**Comment by briandoconnor** [comment]
Hey Brian,

Yes, they did. We are working through the mechanics of granting access now.  We had a call with Google to work things out with them, and there will be another with AWS today. We’ve received the first beta data access request and it looks good, so you should get the green light from Valentina to submit early next week. Our DAC is primed to approve.

 

FYI: In order to deal with the IRB approvals it’s looks like NHLBI is going to set up a central IRB (could be the All of Us IRB) and include reliance language in each OT so that all requests will go through one place that knows what’s going on. Sadly, that’s like to take 1-2 months, but at least you’ll have access to some of the data to get formats right.  Continuing to create mock data sets makes sense for the long term too.

 

A

**Comment by cricketsloan** [comment]
➤ Brian O&#39;Connor commented:

I documented the access process and will close this, creating a new ticket for Michael instead

Tier 1a data access (~10K samples TOPMed, GTEx, MODs) using method 1 and method 2:
See https://drive.google.com/drive/folders/1k6Lr-VdMs_s_b8t3_x_e6lK9aqsb-d3z with the overview from Vivien at https://docs.google.com/document/d/1uuChyp1T5FUYFU_yNEB4XG_vl9jIHBcGX4RBpLN_xZY/edit 
Method 1 AWS access (CGP access coming although we have early access via Goncalo and I asked for full access last week from Jonathan and Albert from Goncalo’s team)
Method 2 (also known as the Sequence Data Delivery Pilot, or SDDP, method), for both CGP and AWS.  Email Nick Weber at nick.weber@nih.gov for early access (who has asked for access?)
What’s Team Calcium’s use of these methods to access the data?
