### ISSUE TITLE
Run WDL workflows in FireCloud on data from HCA DSS via DOS

### ISSUE THREAD

**Issue by mikebaumann** [DataBiosphere/team-lighthouse-point#49]
When will public FC support DOS URLs?

**Comment by mikebaumann** [comment]
Able to execute now with cloud native URLs.

Waiting for update from Broad on public availability of DOS support.

**Comment by wshands** [comment]
Run GTex data through alignment pipeline
Run TopMed CRAMS through variant caller and verify concordance
