### ISSUE TITLE
Boardwalk integration with Firecloud (pass manifest to Firecloud to create/update workspace)

### ISSUE THREAD

**Issue by briandoconnor** [DataBiosphere/team-lighthouse-point#6]
Michael K to coordinate with Phillis and Firecloud folks (David S.?) on the handoff mechanism.  It sounds like both the GDC portal and Broadwalk could make calls to the Firecloud workspace. But it would be best to have an endpoint that we could hand a manifest URL to and have Firecloud automate the creation of a workspace from that.

**Comment by david4096** [comment]
@mjkrause has begun design on a "virtual cohort" or "manifest release" service. Please link docs

**Comment by david4096** [comment]
Manifest handover funcspec https://docs.google.com/document/d/1b4qKQ9apQVop-ejvSKs3ke73rLpk_J0xhR8OPD_eJvU/edit

**Comment by briandoconnor** [comment]
From Moran:

Hi everyone,

Thanks so much for following up on this .  From the product group stands point we were assigning a "driver" for every dev initiative we take part in, and I'll be taking point on our development effort for our team Ca deliverables for the June demo.
With regard to the boardwalk-firecloud integration seems like there are still 2 product questions that need to be scoped :
1) what type of data are we going to index ? Seems like all the metadata we are going to get that someone's really cares about querying is access controlled . ( working on dbGaP submission )
2) did the UCSC and Chicago teams agreed on a scheme and API that will be used for indexing .

Brian, should we have a quick touch base from the product perspective to scope the goals of this work. Who should join this from Chicago ? Phillis ?

Thanks !

Response:

Hi Moran,

Yep, I'm including Phillis here.

Should we have a meeting this week to go over the two items above? As part of 2) I think we can discuss the preliminary design by Michal K., an example BDBag formatted manifest, and the handoff process to FireCloud.  Just to make sure everyone is on the same page and happy with our collective approach?  I especially want to hear Phillis' comments on the manifest format and handoff process (which I think is the simple part) since we want the GDC portal to be able to handoff to Firecloud too.

I think we can decouple a bit the specifics of the metadata from the mechanism to hand off a manifest to a firecloud workspace.  As long as we agree on how to encode this manifest and give it flexibility to encode additional fields of metadata over time.  So that way we can work on collecting and indexing metadata, improving what we have over time.  And, in parallel, devs can work on the handoff of GUIDs for files and additional metadata fields to FireCloud workspaces (via this BDBag handoff process) as well as accessing google native paths by FireCloud via the DOS API on top of either Chicago or UCSC's storage systems.

Only wrinkle to this plan is, like you said Moran, the interesting metadata fields might all be controlled access... in which case a fully open GDC or Boardwalk portal would be a problem.  Do you think we can punt on this for the time being and, later, add a login to the portals (they both already have that functionality)?

Moran, yes, why don't you, me and Phillis have a chat this week as early as possible?  To scope this out.  I'm cc'ing Tina who can help find a time.  Once we're on the same page I think we should have the devs meet up to discuss details.

Brian

**Comment by mjkrause** [comment]
related to the following issues:
BD2K/dcc-dashboard-service#50
BD2K/dcc-dashboard-service#51
BD2K/dcc-dashboard-service#52
BD2K/dcc-ops#155

**Comment by mikebaumann** [comment]
Demo:
Show Firecloud workspace being created, with data loaded, from file browsers (Boardwalk, and Gen 3 Framework Services file browsing portal?)

**Comment by cricketsloan** [comment]
➤ Brian O&#39;Connor commented:

Closing since this was demo'd
