### ISSUE TITLE
Register the WES API with SmartApis

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/team-lighthouse-point#61]
We are supposed to register our API's with:  TO BE FILLED IN

David has done this before, he can help Abraham

**Comment by david4096** [comment]
@achave11 The challenge here is that we need to convert the OpenAPI2 to 3 and then add some keys following their spec.

For example, see the diff between the open api spec, and the smart api spec for DOS here.

https://github.com/david4096/data-object-schemas/tree/smartapi/openapi

This is the command from the README `swagger2openapi -y openapi/data_object_service.swagger.yaml > openapi/data_object_service.openapi.yaml`.

To close this, make a branch with these changes and then set details to the mock wes instance. You can dry run to see if their registry will validate it.

Note! Also add the tag NIHDataCommons to the spec so it shows up in the smartapi registry properly.

**Comment by cricketsloan** [comment]
➤ Abraham Chavez commented:

Here is the URL, with the identifier to the smart-api link
http://smart-api.info/ui/9c7027eec7ba101587f74e4b2ca2f7d2
Taking identifier to be : 9c7027eec7ba101587f74e4b2ca2f7d2
