### ISSUE TITLE
Load mock data in test UCSC Boardwalk

### ISSUE THREAD

**Issue by briandoconnor** [DataBiosphere/team-lighthouse-point#8]
setup mock data in public buckets on AWS and GCP for our stack (and others) to use.

So we have a Boardwalk instance Michael K. and the Firecloud team can prototype with

Need to add geryl and Michael K. to this ticket

**Comment by david4096** [comment]
@briandoconnor will assemble NA12878 and tag Geryl

**Comment by david4096** [comment]
Some data is already in an open access GCS, soon to be S3.

**Comment by david4096** [comment]
Depends on #2

**Comment by cricketsloan** [comment]
➤ David Steinberg commented:

[~casloan] [~mbaumann] can we close based on current state of topmed public? this is a very old ticket

**Comment by cricketsloan** [comment]
➤ Michael Baumann commented:

Yes, this should be closed.
