### ISSUE TITLE
WES mock setup using `wes-service`

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/team-lighthouse-point#82]

**Comment by cricketsloan** [comment]
➤ Abraham Chavez commented:

This is the most basic of the endpoints which returns a json object with information about the service.

Get service-info: [http://wes.ucsc-cgp-dev.org:8080/ga4gh/wes/v1/service-info](http://wes.ucsc-cgp-dev.org:8080/ga4gh/wes/v1/service-info)

And the endpoint for the rest of the calls can be derived from that same endpoint by adjusting the desired path.

Endpoint : [http://wes.ucsc-cgp-dev.org:8080/ga4gh/wes/v1](http://wes.ucsc-cgp-dev.org:8080/ga4gh/wes/v1)
