### ISSUE TITLE
Investigate format of Gen3 JSON export for multiple data sets

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/team-lighthouse-point#94]
Investigate Gen3 107 open access metadata format
Investigate Gen3 GTEx metadata format
Investigate Gen3 MESA metadata format
Investigate Gen3 TOPMed 12k metadata format (not yet loaded into Gen3 as final cloud URLs are not yet available)

**Comment by cricketsloan** [comment]
➤ David Steinberg commented:

Public 107 data has passed the investigation stage and has some kind of data dump.

[https://github.com/david4096/dcp-demo/releases/tag/topmed-public](https://github.com/david4096/dcp-demo/releases/tag/topmed-public)

**Comment by cricketsloan** [comment]
➤ David Steinberg commented:

[~mbaumann] can we close based on https://github.com/david4096/dcp-demo/blob/29bdf9020387bf0500153bbddcccccd57e2d3fad/export-arbitrary-metadata.ipynb ? We can export metadata from the DCP (and they have fine grained ACLs).

**Comment by mikebaumann** [comment]
Yes, this is ready to close, @david4096.
Thanks for your work on this!
